# Generated by Django 3.2.3 on 2021-05-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('image', models.URLField(null=True)),
                ('is_rfa', models.BooleanField(default=False)),
                ('last_bid', models.IntegerField()),
                ('last_bid_time', models.DateTimeField(auto_now=True)),
                ('fpg', models.FloatField(null=True)),
                ('bid_has_ended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_space', models.IntegerField()),
                ('cap_slots', models.SmallIntegerField()),
                ('has_used_to', models.BooleanField(default=False)),
            ],
        ),
    ]
