# Generated by Django 3.2.3 on 2021-06-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeagency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='last_bid_time',
            field=models.DateTimeField(),
        ),
    ]
